# Generated by Django 4.2.16 on 2024-11-27 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_post_excerpt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog_post',
            options={'ordering': ['-created_on']},
        ),
    ]
